### ISSUE TITLE
Fer el camp de EMAILS

### ISSUE THREAD

**Issue by Julss799** [Julss799/PROJECTE1-DAM2#10]
Nom del domini (Defecte: Nom de la compañia)
Extenció del domini (Defecte: .com)

**Comment by Formeinstein13** [comment]
public class GeneradorEmails {

	public static void main(String[] args) {
		   int lineasnom = 0;
		   int lineasCompanyia = 0;
		try {
			File filenom = new File("C:\\Users\\Usuari\\Desktop\\NOMS.txt");
			Scanner scnom = new Scanner(filenom);
			FileReader frnom = new FileReader("C:\\Users\\Usuari\\Desktop\\NOMS.txt");
			BufferedReader brnom = new BufferedReader(frnom);
			while(scnom.hasNextLine()) {
				scnom.nextLine();
		        lineasnom++;
		      }
			scnom.close();
			File fileCompanyia = new File("C:\\Users\\Usuari\\Desktop\\NOMS_DE_COMPANYIES1.txt");
			Scanner scCompanyia = new Scanner(fileCompanyia);
			FileReader frCompanyia = new FileReader("C:\\Users\\Usuari\\Desktop\\NOMS_DE_COMPANYIES1.txt");
			BufferedReader brCompanyia = new BufferedReader(frCompanyia);
			while(scCompanyia.hasNextLine()) {
				scCompanyia.nextLine();
		        lineasCompanyia++;
		      }
			String noms[]= new String[lineasnom];
			String nomsCompanyia[]= new String[lineasCompanyia];
			int i=0;
			while(brnom.ready()) {
				String nom = brnom.readLine();
				noms[i]=nom;
				i++;
			}
			brnom.close();
			frnom.close();
			i=0;
			while(brCompanyia.ready()) {
				String nom = brCompanyia.readLine();
				nomsCompanyia[i]=nom;
				i++;
			}
			brCompanyia.close();
			frCompanyia.close();
			Random numero= new Random();
			int aleatori=0;
			int total;
			String extencio=".com";
			String dominiDemanat="";
			total=150;
			String nomsAleatoris[]= new String[total];
			for(i=0;i<total;i++) {
				aleatori=numero.nextInt(lineasnom);
				nomsAleatoris[i]=noms[aleatori].toLowerCase();
			}
			String companyiesAleatoris[]= new String[total];
			for(i=0;i<total;i++) {
				aleatori=numero.nextInt(lineasCompanyia);
				companyiesAleatoris[i]=nomsCompanyia[aleatori];
			}
			String dominis[]= new String[companyiesAleatoris.length];
			for (i=0;i<companyiesAleatoris.length;i++) {
				String[] parts = companyiesAleatoris[i].split(" ");
				String domini="";
				for (int i2 = 0;i2<parts.length;i2++) {
					domini=domini+parts[i2];
				}
				dominis[i]=domini;
			}
			String emails[]= new String[total];
			if (dominiDemanat.isEmpty()) {
				for (i=0;i<total;i++) {
					emails[i]=nomsAleatoris[i]+"@"+dominis[i]+extencio;
				}
			}
			else {
				for (i=0;i<total;i++) {
					emails[i]=nomsAleatoris[i]+"@"+dominiDemanat+extencio;
				}
			}
			for (i=0;i<emails.length;i++) {
				System.out.println(emails[i]);
			}
		} catch (Exception pasanCosas) {
			pasanCosas.printStackTrace();
		}
	}

}

**Comment by Julss799** [comment]
Falta fer que no es repeteixin
idea: afegir un 1 al nom si l'email està repetit

**Comment by Formeinstein13** [comment]
public class GeneradorEmails {

	public static void main(String[] args) {
		   int lineasnom = 0;
		   int lineasCompanyia = 0;
		try {	//aqui declarem i inicialitzem el fitxer de noms
			File filenom = new File("C:\\Users\\Usuari\\Desktop\\NOMS.txt");
			Scanner scnom = new Scanner(filenom);
			FileReader frnom = new FileReader(filenom);
			BufferedReader brnom = new BufferedReader(frnom);
			//contem les linies del fitxer de noms
			while(scnom.hasNextLine()) {
				scnom.nextLine();
		        lineasnom++;
		      }
			scnom.close();
			//aqui declarem i inicialitzem el fitxer de companyies
			File fileCompanyia = new File("C:\\Users\\Usuari\\Desktop\\NOMS_DE_COMPANYIES1.txt");
			Scanner scCompanyia = new Scanner(fileCompanyia);
			FileReader frCompanyia = new FileReader(fileCompanyia);
			BufferedReader brCompanyia = new BufferedReader(frCompanyia);
			//contem les linies del fitxer de companyies
			while(scCompanyia.hasNextLine()) {
				scCompanyia.nextLine();
		        lineasCompanyia++;
		      }
			scCompanyia.close();
			//declarem els arrays de string del fitxer de noms i del fitxer de companyies
			String noms[]= new String[lineasnom];
			String nomsCompanyia[]= new String[lineasCompanyia];
			int i=0;
			//inicialitzem el array del fitxer de noms
			while(brnom.ready()) {
				String nom = brnom.readLine();
				noms[i]=nom;
				i++;
			}
			brnom.close();
			frnom.close();
			i=0;
			//inicialitzem el array del fitxer de companyies
			while(brCompanyia.ready()) {
				String nom = brCompanyia.readLine();
				nomsCompanyia[i]=nom;
				i++;
			}
			brCompanyia.close();
			frCompanyia.close();
			Random numero= new Random();
			//declarem i inicialitzem les variables basiques
			int aleatori=0;
			int total;
			String extencio=".com";
			String dominiDemanat="";
			total=150;
			//declarem els arrays per barrejar el fitxer de noms i de companyies
			String nomsAleatoris[]= new String[total];
			String nomsRepetits[]= new String[total];
			//declarem el arrai per canviar el nom dels noms repetits
			String NumerosNomsRepetits[]= new String[total];
			//inicialitzem el array per canviar el nom dels noms repetits
			for (i=0;i<total;i++){
				NumerosNomsRepetits[i]="";
			}
			//inicialitzem el array per barrejar el fitxer de noms
			for(i=0;i<total;i++) {
				aleatori=numero.nextInt(lineasnom);
				nomsAleatoris[i]=noms[aleatori].toLowerCase();
				nomsRepetits[i]=nomsAleatoris[i];
			}
			//funcio per a poder canviar el nom dels que estan repetits
			for(i=0;i<total;i++) {
				for (int i2 = 0;i2<nomsRepetits.length;i2++) {
					int fin=nomsRepetits.length-2;
					if (i2<fin&&nomsAleatoris[i].equals(nomsRepetits[i2+1])) {
						aleatori=numero.nextInt(lineasnom);
						String temp=nomsAleatoris[i];
						NumerosNomsRepetits[i]=NumerosNomsRepetits[i]+1;
						nomsAleatoris[i]=temp+NumerosNomsRepetits[i];
					}
				}
			}
			//declarem el array per barrejar el fitxer de companyies
			String companyiesAleatoris[]= new String[total];
			//inicialitzem el array per barrejar el fitxer de companyies
			for(i=0;i<total;i++) {
				aleatori=numero.nextInt(lineasCompanyia);
				companyiesAleatoris[i]=nomsCompanyia[aleatori];
			}
			//inicialitzem el array de dominis per crear els dominis a partir de el nom de la companyia
			String dominis[]= new String[companyiesAleatoris.length];
			//inicialitzem el array que crea els dominis
			for (i=0;i<companyiesAleatoris.length;i++) {
				String[] parts = companyiesAleatoris[i].split(" ");
				String domini="";
				for (int i2 = 0;i2<parts.length;i2++) {
					domini=domini+parts[i2];
				}
				dominis[i]=domini;
			}
			//declarem el array per crear els emails
			String emails[]= new String[total];
			//inicialitzem el array per crear els emails
			//aquest if es per saver si no hi ha un domini solicitat
			if (dominiDemanat.isEmpty()) {
				for (i=0;i<total;i++) {
					emails[i]=nomsAleatoris[i]+"@"+dominis[i]+extencio;
				}
			}
			//aquest else es per saver si hi ha un domini solicitat
			else {
				for (i=0;i<total;i++) {
					emails[i]=nomsAleatoris[i]+"@"+dominiDemanat+extencio;
				}
			}
			//mostrem el emais de l'array d'emails
			for (i=0;i<emails.length;i++) {
				System.out.println(emails[i]);
			}
		} catch (Exception pasanCosas) {
			pasanCosas.printStackTrace();
		}
	}

}
