### ISSUE TITLE
Fer el camp de DATES

### ISSUE THREAD

**Issue by Julss799** [Julss799/PROJECTE1-DAM2#12]
Any mínim (Defecte: 1900)
Any màxim (Defecte: 2023)

**Comment by Julss799** [comment]
import java.util.Random;
import java.util.Scanner;

public class Dates {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		int dia, mes, any, anyMax, anyMin, parametres, i, interval;
		Random bombo=new Random(); //maxim un cop per programa
		Scanner teclat = new Scanner(System.in);
		
		//Donem els valors per defecte
		anyMax=2023;
		anyMin=1900;
		
		System.out.println("Vols introduir parametres? 1-Si 2- No");
		parametres=teclat.nextInt();
		
		if(parametres==1) //Si vol parametres mirarem si nomes vol any minim o si vol els dos.
		{
			System.out.println("Any Mínim: ");
			anyMin=teclat.nextInt();
			System.out.println("Vols indicar any Maxim? 1-Si 2-No");
			parametres=teclat.nextInt();
			if(parametres==1)
			{
				System.out.println("Any Máxmin: ");
				anyMax=teclat.nextInt();
			}
		}
		
		System.out.println("Quants valors vols imprimir?");
		i=teclat.nextInt();
		
		interval=anyMax-anyMin+1; //Calculem el interval per a generar els anys aleatoris dins del rang
		
		while(i>0)
		{
			dia=1+bombo.nextInt(31);
			mes=1+bombo.nextInt(12);
			any=anyMin+bombo.nextInt(interval);
			System.out.println(dia+"/"+mes+"/"+any);
			i--;
		}
		
	}

}

**Comment by Julss799** [comment]
Falta validar les dades (ex: 31/02/2022)

**Comment by eliasporter** [comment]
//Demanem dades per teclat
		Scanner lector=new Scanner(System.in);
		System.out.print("Introdueix un any i et dire si es bixest: ");
		any=lector.nextInt();		
		//Calculem
		if(any%4==0) {
			if(any%100==0) {
				if(any%400==0) {
					System.out.print("Es bixest!");
				}
				else {
					System.out.print("No es bixest!");
				}
			}
			else {
				System.out.print("Es bixest!");		
			}
		}
		else {
			System.out.print("No es bixest!");
		}

**Comment by Julss799** [comment]
import java.util.Random;
import java.util.Scanner;

public class Dates {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		int dia=0, mes, any, anyMax, anyMin, parametres, i, interval;
		Random bombo=new Random(); //maxim un cop per programa
		Scanner teclat = new Scanner(System.in);
		
		//Donem els valors per defecte
		anyMax=2023;
		anyMin=1900;
		
		System.out.println("Vols introduir parametres? 1-Si 2- No");
		parametres=teclat.nextInt();
		
		if(parametres==1) //Si vol parametres mirarem si nomes vol any minim o si vol els dos.
		{
			System.out.println("Any Mínim: ");
			anyMin=teclat.nextInt();
			System.out.println("Vols indicar any Maxim? 1-Si 2-No");
			parametres=teclat.nextInt();
			if(parametres==1)
			{
				System.out.println("Any Máxmin: ");
				anyMax=teclat.nextInt();
			}
		}
		
		System.out.println("Quants valors vols imprimir?");
		i=teclat.nextInt();
		
		interval=anyMax-anyMin+1; //Calculem el interval per a generar els anys aleatoris dins del rang
		
		while(i>0)
		{
			mes=1+bombo.nextInt(12);
			any=anyMin+bombo.nextInt(interval);
			if (mes==1 || mes==3 || mes==5 || mes==7 || mes==8 || mes==10 || mes==12)
			{
				dia=1+bombo.nextInt(31);
			}
			else if (mes==2)
			{
				if(any%4==0) {
					if(any%100==0) {
						if(any%400==0) {
							dia=1+bombo.nextInt(29);
						}
						else {
							dia=1+bombo.nextInt(28);
						}
					}
					else {
						dia=1+bombo.nextInt(29);
					}
				}
				else {
					dia=1+bombo.nextInt(28);
				}
			}
			else
			{
				dia=1+bombo.nextInt(30);
			}
			System.out.println(dia+"/"+mes+"/"+any);
			i--;
		}
		
	}

}
