### ISSUE TITLE
Fer el camp de IBAN

### ISSUE THREAD

**Issue by Julss799** [Julss799/PROJECTE1-DAM2#13]

**Comment by Julss799** [comment]
Realitzar una investigació dels bancs existents

**Comment by Julss799** [comment]
[https://medium.com/@manuelmato/c%C3%B3mo-validar-una-cuenta-bancaria-en-java-49268b2596c6](https://medium.com/@manuelmato/c%C3%B3mo-validar-una-cuenta-bancaria-en-java-49268b2596c6)

**Comment by eliasporter** [comment]
La primera aproximació intentant generar els 4 digits dels bancs i els 4 digits de la oficina no ha funcionat, al comprovar els iban's generats, no son valids.

**Comment by eliasporter** [comment]
Realitzant una busqueda intensiva dels bancs i oficines presents a la provincia de Lleida i generarem iban's aleatoris de bancs i oficines de la mateixa.

**Comment by eliasporter** [comment]
`package projecte1;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.math.BigInteger;
import java.nio.file.DirectoryIteratorException;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Random;
import java.util.Scanner;

public class IBAN {

	public static void main(String[] args) {
		int contador=0, tamany=0, banc, oficina, control1, control2, A=0, B=0, C, D=0, E;
		Random r = new Random();
		String BancsLleida[]=new String[1], oficinesBanc[]=new String[1], bancOficina="", compte="", IBAN, IBANsenseCC, CCC="", nomFitxer="", Rstring;
		boolean finalitzador=false;
		
		//Llegim l'arxiu dels bancs presents a la provincia de Lleida
		try {
			File f1 = new File("c:\\Projecte1\\BancsLleida.txt");
			Scanner s = new Scanner(f1);
			FileReader fr = new FileReader(f1);
			BufferedReader br = new BufferedReader(fr);
			while(s.hasNextLine()) {
				s.nextLine();
				contador++;
			}
			tamany=contador;
			BancsLleida=new String[tamany];
			contador=0;
			while(contador<tamany) {
				BancsLleida[contador]=br.readLine();
				contador++;
			}
			contador=0;
		}catch (Exception e) {	
		}
		//Elegim el banc aleatoriament
		banc=r.nextInt(tamany);
		
		//Un cop tenim el banc, carreguem les seves oficines
		Path dir = Paths.get("c:\\projecte1\\");
		try (DirectoryStream<Path> stream = Files.newDirectoryStream(dir);) {
			for (Path fitxer: stream) {
				if (finalitzador==true) {
					break;
				}
				nomFitxer=fitxer.toString();
				if (nomFitxer.startsWith("c:\\projecte1\\"+BancsLleida[banc])) {
					File f2 = new File(fitxer.toString());
					Scanner s2 = new Scanner(f2);
					FileReader fr2 = new FileReader(f2);
					BufferedReader br2 = new BufferedReader(fr2);
					while(s2.hasNextLine()) {
						s2.nextLine();
						contador++;
					}
					tamany=contador;
					oficinesBanc=new String[tamany];
					contador=0;
					while(contador<tamany) {
						oficinesBanc[contador]=br2.readLine();
						contador++;
					}
					contador=0;
					finalitzador=true;
				}
			}
		} catch (IOException | DirectoryIteratorException ex) {
			System.err.println(ex);
		}
		
		//Elegim la oficina aleatoriament
		oficina=r.nextInt(tamany);
		
		//Completem banc i oficina
		bancOficina=BancsLleida[banc]+oficinesBanc[oficina];
		
		//Generem el compte
		for(int i = 0; i < 10; i++){
	        compte += r.nextInt(10);
	    }
		
		
		//Calculem el primer digit de control
		for (int i = 0; i < bancOficina.length(); i++) {
			if(i==0) {
				A+=Character.getNumericValue(bancOficina.charAt(i))*4;
			}
			if(i==1) {
				A+=Character.getNumericValue(bancOficina.charAt(i))*8;
			}
			if(i==2) {
				A+=Character.getNumericValue(bancOficina.charAt(i))*5;
			}
			if(i==3) {
				A+=Character.getNumericValue(bancOficina.charAt(i))*10;
			}
			if(i==4) {
				B+=Character.getNumericValue(bancOficina.charAt(i))*9;
			}
			if(i==5) {
				B+=Character.getNumericValue(bancOficina.charAt(i))*7;
			}
			if(i==6) {
				B+=Character.getNumericValue(bancOficina.charAt(i))*3;
			}
			if(i==7) {
				B+=Character.getNumericValue(bancOficina.charAt(i))*6;
			}
		}
		C=(A+B)%11;
		control1=11-C;
		if (control1==10) {
			control1=1;
		}
		if (control1==11) {
			control1=0;
		}
		//Calculem el 2n digit de control
		for (int i = 0; i < compte.length(); i++) {
			if(i==0) {
				D+=Character.getNumericValue(compte.charAt(i))*1;
			}
			if(i==1) {
				D+=Character.getNumericValue(compte.charAt(i))*2;
			}
			if(i==2) {
				D+=Character.getNumericValue(compte.charAt(i))*4; 
			}
			if(i==3) {
				D+=Character.getNumericValue(compte.charAt(i))*8; 
			} 
			if(i==4) {
				D+=Character.getNumericValue(compte.charAt(i))*5; 
			}
			if(i==5) {
				D+=Character.getNumericValue(compte.charAt(i))*10;
			}
			if(i==6) {
				D+=Character.getNumericValue(compte.charAt(i))*9;
			}
			if(i==7) {
				D+=Character.getNumericValue(compte.charAt(i))*7;
			}
			if(i==8) {
				D+=Character.getNumericValue(compte.charAt(i))*3;
			}
			if(i==9) {
				D+=Character.getNumericValue(compte.charAt(i))*6;
			}
		}
		E=D%11;
		control2=11-E;
		if (control2==10) {
			control2=1;
		}
		if (control2==11) {
			control2=0;
		}
		CCC=bancOficina+control1+control2+compte;
		
		//Calculem els digits de control de l'IBAN
		IBANsenseCC=CCC+14+28;
		
		BigInteger calcularIban=new BigInteger(IBANsenseCC);
		BigInteger mod97 = new BigInteger("97");
		BigInteger RBigInt=calcularIban.mod(mod97);
		
		Rstring=RBigInt.toString();
		
		if (Rstring.length()<2) {
			IBAN="ES0"+Rstring+CCC;			
		}else {
			IBAN="ES"+Rstring+CCC;
		}
		//Publiquem IBAN, que sera el return de la funcio
		System.out.println(IBAN);
	}

}`

**Comment by Julss799** [comment]
while(br.ready()) { //mentre hi hagi lineas
			marc = br.readLine();
			System.out.println(marc);
		}
//Perquè llegeixi mentre hi hagi línies i evitar mirar primer quantes hi ha a l'arxiu
