### ISSUE TITLE
Fer el camp de AUTONUMÉRIC

### ISSUE THREAD

**Issue by Julss799** [Julss799/PROJECTE1-DAM2#15]
Valor d'inici (Defecte: 1)

**Comment by eliasporter** [comment]
package projecte1;

public class autonumeric {

	public static void main(String[] args) {
		int inici=0; //valor d'inici de l'autonumeric definit al arxiu d'entrada, per defecte 0
		int registres=100; //el que rebra la funcio del main depenent de la quantitat de registres demanats
		int resultat=0; //el valor que retornara la funcio
		
		for (int i = 0; i < registres; i++) {
			resultat=inici;
			inici++;
			System.out.println(resultat);
		}
	}
	
}
