### ISSUE TITLE
Realitzar l'esquema d'execució del programa final amb Lucid

### ISSUE THREAD

**Issue by Julss799** [Julss799/PROJECTE1-DAM2#16]

**Comment by eliasporter** [comment]
https://lucid.app/lucidchart/d11a38c3-78bf-4679-a59e-b9730a7ad53b/edit?viewport_loc=-246%2C1407%2C2426%2C1145%2C0_0&invitationId=inv_ba33dd99-deda-4185-8a5b-2f52ff80e73f#
