### ISSUE TITLE
Instal·lació  XAMPP

### ISSUE THREAD

**Issue by ghost** [Julss799/PROJECTE1-DAM2#29]

**Comment by JoseProgramadorMaster** [comment]
S'ha de canviar el port del mysql

**Comment by eliasporter** [comment]
> S'ha de canviar el port del mysql

Posa 666

**Comment by ghost** [comment]
He ficat 6969

**Comment by JoseProgramadorMaster** [comment]
![image](https://user-images.githubusercontent.com/114421882/194901322-c3fad838-31bb-4748-8009-bd7e9176e92c.png)
