### ISSUE TITLE
Fer el camp de BOOLEANS

### ISSUE THREAD

**Issue by Julss799** [Julss799/PROJECTE1-DAM2#7]

**Comment by Formeinstein13** [comment]
import java.util.Random;

public class GeneradorBooleans {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Random numero= new Random();
		boolean aleatori;
		int numeroAleatori=numero.nextInt(2);
		if (numeroAleatori==0){
			aleatori=false;
		}
		else {
			aleatori=true;
		}
		System.out.println(aleatori);
	}

}

**Comment by ghost** [comment]
import java.util.Random;

public class booleans {
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Random numero= new Random();
		boolean aleatori; //variable on es guarda boolean
		int numeroAleatori=numero.nextInt(2); //numeros aleatoris de 2 digits
		if (numeroAleatori==0){ //si es 0, sortira boolean false
			aleatori=false;
		}
		else {
			aleatori=true; //i si surt 1, sortira boolean true
		}
		System.out.println(aleatori); //mostrem per pantalla
	}
}
