### ISSUE TITLE
Realitzar proves de rendiment de l'aplicació

### ISSUE THREAD

**Issue by eliasporter** [Julss799/PROJECTE1-DAM2#78]

**Comment by Julss799** [comment]
He trobat problemes quan generem mes de 10000 registres amb el SQL i el XML, amb el CSV els genera bé

**Comment by Julss799** [comment]
Hem trobat problemes amb la generació dels emails

**Comment by Julss799** [comment]
Ja hem solucionat, i hem aumentat el rendiment de l'aplicació
