### ISSUE TITLE
Fer el camp de NUMBER

### ISSUE THREAD

**Issue by Julss799** [Julss799/PROJECTE1-DAM2#9]
Decimals (Defecte 0)
Mínim (Defecte 0)
Màxim (Defecte 1000)

**Comment by Formeinstein13** [comment]
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.Random;

public class NUMBERS {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Random numero= new Random();
		int quantsDecimals=0;
		int contador=0;
		int total=300;
		int maxim=1000;
		int minim=0;
		
		maxim=maxim-minim;
		    
		while(contador<total) {
			double generat=numero.nextDouble(maxim)+minim;
			 BigDecimal redondeado = new BigDecimal(generat)
	                 .setScale(quantsDecimals, RoundingMode.HALF_EVEN);
			System.out.println(contador+"-"+redondeado);
			contador++;
	}
	}
}

**Comment by Julss799** [comment]
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.Random;

public class NUMBERS {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Random numero= new Random();
		int quantsDecimals=0;
		int contador=0;
		int total=100;
		int maxim=10;
		int minim=8;
		
		if (minim>=maxim)
		{
			System.out.println("error");
		}
		else
		{
			maxim=maxim-minim;
			while(contador<total) {
				double generat=numero.nextDouble(maxim)+minim;
				 BigDecimal redondeado = new BigDecimal(generat)
		                 .setScale(quantsDecimals, RoundingMode.HALF_EVEN);
				System.out.println(contador+"-"+redondeado);
				contador++;
		}
		}
		
	}
}
